[package]
name = "gr_compact_objects"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"

[lib]
name = "gr_compact_objects"
path = "src/lib.rs"

[workspace]
members = ["research_project"]

